kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          volumeMounts:
            - name: index-html
              mountPath: {{ .Values.volumes.mount.path }} # this will mount the html.index file to it application location
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }} # this check the application url path
              port: {{ .Values.containers.containerPort }} # In which port the Application is listening
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }} # the abount of time to wait between checks
            successThreshold: {{ .Values.probes.readiness.successThreshold }} # count to decalre seccessfull 
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }} # count to decalre failure
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveliness.path }}
              port: {{ .Values.containers.containerPort }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probes.liveliness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.liveliness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.liveliness.periodSeconds }} # the abount of time to wait between checks
            successThreshold: {{ .Values.probes.liveliness.successThreshold }} # count to decalre seccessfull 
            failureThreshold: {{ .Values.probes.liveliness.failureThreshold }} # count to decalre failure
          env:
          - name: PORT
            value: {{ .Values.containers.containerPort | quote }}
      volumes:
        - name: index-html
          configMap:
            name: index.html
            defaultMode: 420
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10